# wrangler.toml

# This is your Cloudflare Pages project name.
# Find it in your Cloudflare dashboard under Workers & Pages -> [Your Project Name].
# It must match EXACTLY.
name = "cafecterapia.monarquiaconstitucionalista.workers.dev" 

# This ensures your project uses a stable version of the Cloudflare runtime.
# Using a recent date is good practice.
compatibility_date = "2024-04-05"

# Add this new section that Cloudflare is asking for.
# This enables real-time logging for your deployment.
[observability.logs]
enabled = true
